name: Build and deploy container app to Azure Web App - ebiznes-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jelon97/ebiznes2021:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ebiznes-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7d437757e63d4f5aa9304617ab190477 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4598bb610b6a4b1891a29c163b243272 }}/jelon97/ebiznes2021:${{ github.sha }}'
