# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ebiznes-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_4598bb610b6a4b1891a29c163b243272 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6c9ad8f8c7c048bfa0f3f31f3360a42f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4598bb610b6a4b1891a29c163b243272 }}/jelon97/ebiznes2021:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ebiznes-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7d437757e63d4f5aa9304617ab190477 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4598bb610b6a4b1891a29c163b243272 }}/jelon97/ebiznes2021:${{ github.sha }}'